### ISSUE TITLE
work - 뷰페이지에서 X 버튼으로 돌아왔을 때

### ISSUE THREAD

**Issue by designbycasker** [casker-pokbab/portfolio#63]
'더 많은 포트폴리오 불러오기' 버튼 누른 후

포트폴리오에서 뷰 페이지로 들어간 후, X 버튼으로 돌아왔을 때

포트폴리오 열려있던 상태로 놔두기

**Comment by Pokbab** [comment]
"뒤로가기" 이벤트에 대한 대응이 안됨.
새창/창닫기 형태로 전환
